# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: Hosted Agent

stages:
  - stage: dev
    jobs:
      - job:
        steps:
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: 'Azure subscription 1(76589609-f356-45d6-9343-cacd37492e24)'
              subscriptionId: '76589609-f356-45d6-9343-cacd37492e24'
              action: 'Create Or Update Resource Group'
              resourceGroupName: 'mrcloudrg'
              location: 'UK South'
              templateLocation: 'Linked artifact'
              csmFile: 'https://github.com/Ravipati989/modules/blob/main/arm.json'
              deploymentMode: 'Incremental'